force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Account__c/Custom_Account__c.object-meta.xml
<CustomObject>
    <label>Custom Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Account__c/fields/DateTime__c.field-meta.xml
<CustomField>
    <fullName>DateTime__c</fullName>
    <label>DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Custom_Account__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Apparel</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Biotechnology</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
            <value>
                <fullName>Environmental</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Food &amp; Beverage</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Machinery</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Not For Profit</fullName>
            </value>
            <value>
                <fullName>Recreation</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>Telecommunications</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Account__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Custom Accounts</relationshipLabel>
    <relationshipName>Custom_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Case__c/Custom_Case__c.object-meta.xml
<CustomObject>
    <label>Custom Case</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>CaseNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Case__c/fields/Datetime__c.field-meta.xml
<CustomField>
    <fullName>Datetime__c</fullName>
    <label>Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Custom_Case__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Custom Cases</relationshipLabel>
    <relationshipName>Custom_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Contact__c/Custom_Contact__c.object-meta.xml
<CustomObject>
    <label>Custom Contact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Contact__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Custom Contacts</relationshipLabel>
    <relationshipName>Custom_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Contact__c/fields/Pronouns__c.field-meta.xml
<CustomField>
    <fullName>Pronouns__c</fullName>
    <label>Pronouns</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>He/Him</fullName>
            </value>
            <value>
                <fullName>She/Her</fullName>
            </value>
            <value>
                <fullName>They/Them</fullName>
            </value>
            <value>
                <fullName>He/They</fullName>
            </value>
            <value>
                <fullName>She/They</fullName>
            </value>
            <value>
                <fullName>Not Listed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Contract__c/Custom_Contract__c.object-meta.xml
<CustomObject>
    <label>Custom Contract</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>ContractNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Contract__c/fields/Activated_Date__c.field-meta.xml
<CustomField>
    <fullName>Activated_Date__c</fullName>
    <label>Activated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Custom_Contract__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Custom Contracts</relationshipLabel>
    <relationshipName>Custom_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Approval Process</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DynamicTableController_Test.cls
/**
 * This is a test class for DynamicTableController class.
 * @author Gaurav Kumar
 * @since  11 April 2023
 */
@IsTest
public with sharing class DynamicTableController_Test {
    @testSetup
    private static void testSetup() {
        Account a = new Account(Name='Test Account', Status__c='Open');
        insert a;
        List<SObject> recordList = new List<SObject>();
        for (Integer i = 0; i < 200; i++) {
            recordList.add(new Custom_Account__c(Name='Test Account ' + (i + 1), Rating__c='Hot', DateTime__c= DateTime.now(), Industry__c='Education', Parent_Account__c=a.Id));
        }
        for (Integer i = 0; i < 200; i++) {
            recordList.add(new Custom_Contact__c(Name='Test Contact ' + (i + 1), Date__c=Date.today(), Pronouns__c='He/Him', Parent_Account__c=a.Id));
        }
        for (Integer i = 0; i < 200; i++) {
            recordList.add(new Custom_Case__c(Datetime__c=DateTime.now(), Description__c='This is case discription',Status__c='New', Parent_Account__c=a.Id));
        }
        for (Integer i = 0; i < 200; i++) {
            recordList.add(new Custom_Contract__c(Activated_Date__c=DateTime.now(), Description__c='This is contract discription',Status__c='Activated', Parent_Account__c=a.Id));
        }
        insert recordList;
    }

    @IsTest
    static void testGetDataWithValidInput(){
        String accountName = 'Custom_Account__c';
        List<String> fields = new List<String>{'Name', 'Rating__c', 'DateTime__c', 'Industry__c'};
        Test.startTest();
            List<Custom_Account__c> accountList = DynamicTableController.getData(accountName, fields);
        Test.stopTest();
        System.assertEquals(200, accountList.size(), 'There should have been 200 records in the Custom_Account__c SObject');
    }

    @IsTest
    static void testGetDataWithInvalidInput(){
        String accountName = 'Custom_Contact__c';
        List<String> fields = new List<String>{'Name', 'Rating__c', 'DateTime__c', 'Industry__c'};
        Test.startTest();
            try {
                DynamicTableController.getData(accountName, fields);
            }
            catch (Exception e) {
                System.assertEquals(true, e.getMessage().contains('Script-thrown'), 'Error message must contain Script-Thrown Error');
            }
        Test.stopTest();
    }
}