force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Account__c/Custom_Account__c.object-meta.xml
<CustomObject>
    <label>Custom Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Account__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Custom Accounts</relationshipLabel>
    <relationshipName>Custom_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Case__c/Custom_Case__c.object-meta.xml
<CustomObject>
    <label>Custom Case</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>CaseNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Case__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Custom Cases</relationshipLabel>
    <relationshipName>Custom_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Contact__c/Custom_Contact__c.object-meta.xml
<CustomObject>
    <label>Custom Contact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Contact__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Custom Contacts</relationshipLabel>
    <relationshipName>Custom_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Contract__c/Custom_Contract__c.object-meta.xml
<CustomObject>
    <label>Custom Contract</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>ContractNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Contract__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Custom Contracts</relationshipLabel>
    <relationshipName>Custom_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Approval Process</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DynamicTableController.cls
/**
 * Controller class for TableContainer and TableWrapper LWC components
 * Test Class - DynamicTableController_Test
 * @author Gaurav Kumar
 * @since  11 April 2023
 */
public with sharing class DynamicTableController {
    /**
     * This method is used to fetch records of an SObject
     * Please use this method to retrieve record of 'Custom_Account__c', 'Custom_Contact__c', 'Custom_Case__c', 'Custom_Contract__c' only.
     * Otherwise it may through exception.
     * @param objectName API name of the SObject that's records to be retrieved
     * @param fields     API name of fields that's values should be retrieved
     * @return           `List<SObject>`
     * @exception        AuraHandledException
     */
    @AuraEnabled
    public static List<SObject> getData(String objectName, List<String> fields) {
        List<SObject> objList = new List<SObject>();
        try {
            if (!String.isBlank(objectName) && fields != null) {
                String query = String.escapeSingleQuotes('SELECT ' + String.join(fields, ',') + ',Parent_Account__r.Status__c FROM ' + objectName);
                objList.addAll(Database.query(query));
            }
        }
        catch (Exception ex) {
            throw new AuraHandledException('Object API Name or One of the merge field name is incorrect. Make sure that the SObject and its fields exists.');
        }
        return objList;
    }

    /**
     * This method is used to insert or update SObjects
     * @param objectName API Name of the SObject that's records to be saved
     * @param fields     A map that contains field -> value for the specified SObject
     * @return           `List<SObject>`
     */
    @AuraEnabled
    public static List<SObject> saveData(String objectName, List<Map<String, Object>> records, Map<String, String> fieldTypes) {
        try {
            List<SObject> objList = new List<SObject>();
            Database.UpsertResult[] result;
            if (!String.isBlank(objectName) && records != null && fieldTypes != null) {
                Map<String, Schema.SObjectType> globalDescribe = Schema.getGlobalDescribe();
                for (Map<String, Object> record : records) {
                    SObject obj = globalDescribe.get(objectName).newSObject();
                    for (String field : record.keySet()) {
                        if (record.get(field) != null) {
                            if ('datetime'.equalsIgnoreCase(fieldTypes.get(field)?.toLowerCase())) {
                                Datetime dt = Datetime.valueOf(((String) record.get(field)).replace('T', ' ').substringBefore('.').replace('Z', ''));
                                obj.put(field, dt);
                            }
                            else if ('date'.equalsIgnoreCase(fieldTypes.get(field)?.toLowerCase())) {
                                Date d = Date.valueOf((String) record.get(field));
                                obj.put(field, d);
                            }
                            else {
                                obj.put(field, (String)record.get(field));
                            }
                        }
                    }
                    objList.add(obj);
                }

                Schema.DescribeSObjectResult describeResult = globalDescribe.get(objectName).getDescribe();
                if (describeResult.isUpdateable() && describeResult.isCreateable()) {
                    result =  Database.upsert(objList);
                }
            }
            return getCreatedRecords(result, objectName, new List<String>(fieldTypes.keySet()));
        }
        catch (Exception ex) {
            throw new AuraHandledException('Object API Name or One of the merge field name is incorrect. Make sure that the SObject and its fields exists.');
        }
    }

    @TestVisible
    private static List<SObject> getCreatedRecords(List<Database.UpsertResult> result, String objectName, List<String> fields) {
        try {
            Set<Id> createdRecordIds = new Set<Id>();
            for (Database.UpsertResult r : result) {
                if (r.isCreated()) {
                    createdRecordIds.add(r.getId());
                }
            }
            String query = String.escapeSingleQuotes('SELECT ' + String.join(fields, ',') + ',Parent_Account__r.Status__c FROM ' + objectName + ' WHERE ID IN :createdRecordIds');
            return Database.query(query);
        }
        catch (Exception ex) {
            throw new AuraHandledException('Error fetching created records');
        }
    }
}